### ISSUE TITLE
sip Unable to find file "QtCore/QtCoremod.sip" 

### ISSUE THREAD

**Issue by iPaddy** [ros-noetic-arch/ros-noetic-python-qt-binding#2]
I don't know exactly if here is the right place to post this issue. But I had problems installing ros-noetic-qt-gui-cpp because of an error in 
/opt/ros/noetic/share/python_qt_binding/cmake/sip_configure.py

where in line 57 and 62 both a default_sip_dir is defined but the first one crashed because with the error:
sip Unable to find file "QtCore/QtCoremod.sip"

commenting out lines 57-59 fixed the problem. 
There probably just has to be a conditional beforehand checking for python3.
Any idea where to put the corresponding pull request? If it is valid anyways...

**Comment by acxz** [comment]
Corresponding ros-melodic issue: https://github.com/ros-melodic-arch/ros-melodic-rviz/issues/9
and corresponding upstream issue: https://github.com/ros-visualization/python_qt_binding/issues/80

**Comment by acxz** [comment]
Using upstream sip path patch in 7dcebf0.

@iPaddy can you confirm if the updated package (0.4.3-2) works for you with the downstream packages that depend on it like `ros-noetic-qt-gui-cpp`?

**Comment by acxz** [comment]
Patch has been released in new version
