### ISSUE TITLE
sha256sum validation fails for sip_path.patch

### ISSUE THREAD

**Issue by PaioPaio** [ros-noetic-arch/ros-noetic-python-qt-binding#3]
Building ros-noetic-desktop-full on manjaro with pacman fails when the process reaches ros-noetic-python-qt-binding and stops throwing 

```
==> Validating source file with sha256sums...
    ros-noetic-python-qt-binding-0.4.3.tar.gz ... Verified
    sip_path.patch ... FAILED

```
(translated).

Is this on my end or an actual issue ?

**Comment by Mad0Scientisto** [comment]
I've had the same problem. I solved it by changing the second value of sha256sums of the PKGBUILD file. To get the new value I downloaded with wget the file "https://patch-diff.githubusercontent.com/raw/ros-visualization/python_qt_binding/pull/95.patch", which according to the .SRCINFO file corresponds to "sip_path. patch", and then I calculated the SHA via linux command 'sha256sums'.

**Comment by acxz** [comment]
If  you could make an associated PR that would be much appreciated!

**Comment by PaioPaio** [comment]
Yeah I can confirm that this works, thanks @Mad0Scientisto
